spring.application.name=clientEntity-service
spring.data.r2dbc.repositories.enabled=true
spring.r2dbc.url=r2dbc:postgresql://pg-dfbdb02-galobsc-ecd5.l.aivencloud.com:15255/defaultdb?sslmode=require
spring.r2dbc.username=avnadmin
spring.r2dbc.password=AVNS_Fnix-ea89rAfzX3oSx4


# security
config.aes.initvector=PruebaTecnicaDBP
config.aes.secret=kdx0S6GP0SIqZqUYGgexm1x1xIUobBBh